### ISSUE TITLE
Swift 2.3 build error

### ISSUE THREAD

**Issue by klwoon** [CosynPa/TZStackView#4]
```
/Users/klwoon/Documents/projects/work/Pods/TZStackView/TZStackView/TZStackView.swift:250:46: error: cannot assign value of type 'TZFuncAnimationDelegate' to type 'CAAnimationDelegate?'
                callbackAnimation.delegate = TZFuncAnimationDelegate { _ in
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/klwoon/Documents/projects/work/Pods/TZStackView/TZStackView/TZStackView.swift:785:74: error: 'Baseline' is unavailable in Swift: Use 'lastBaseline' instead
                constraints += equalAttributes(views: views, attribute: .Baseline)
                                                                         ^~~~~~~~
UIKit.NSLayoutAttribute:16:23: note: 'Baseline' has been explicitly marked unavailable here
    public static var Baseline: NSLayoutAttribute { get }
                      ^

```

Build with XCode 8 Swift 2.3 failed with these errors. Could you suggest any fix? Thank you.

**Comment by CosynPa** [comment]
Fixed in swift2.3 branch
